In [1]:
import numpy as np
import random

from timeit import timeit

def add_python(Z1, Z2):
  return [Z1 + Z2 for Z1, Z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
  return np.add(Z1, Z2)

Z1 = random.sample(range(1000), 100)
Z2 = random.sample(range(1000), 100)

python_time = timeit("add_python(Z1, Z2)", globals=globals(), number=10000)
numpy_time = timeit("add_numpy(Z1,Z2)", globals=globals(), number = 10000)

print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"Numpy addition: {numpy_time:.2f} s per loop")

Pure Python addition: 0.09 s per loop
Numpy addition: 0.15 s per loop


In [2]:
import numpy as np
import random

from timeit import timeit

def add_python(Z1, Z2):
  return [Z1 + Z2 for Z1, Z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
  return np.add(Z1, Z2)

size = 1000000
Z1_list = random.sample(range(size + 1), size)
Z2_list = random.sample(range(size + 1), size)

Z1 = np.array(Z1_list)
Z2 = np.array(Z2_list)

# Z1 = random.sample(range(1000), 100)
# Z2 = random.sample(range(1000), 100)

python_time = timeit("add_python(Z1, Z2)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1,Z2)", globals=globals(), number = 100)

print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"Numpy addition: {numpy_time:.2f} s per loop")

Pure Python addition: 22.59 s per loop
Numpy addition: 0.15 s per loop


In [3]:
import numpy as np
# Create and display zero , one , and n- dimensional arrays
zero_dim_array = np . array (5)
one_dim_array = np . array ([1 , 2 , 3])
n_dim_array = np . array ([[1 , 2] , [3 , 4]])
for arr in [ zero_dim_array , one_dim_array , n_dim_array ]:
  print(f" Array :\n {arr } \n Dimension : {arr. ndim }\n Data type :{arr. dtype } \n")

 Array :
 5 
 Dimension : 0
 Data type :int64 

 Array :
 [1 2 3] 
 Dimension : 1
 Data type :int64 

 Array :
 [[1 2]
 [3 4]] 
 Dimension : 2
 Data type :int64 



In [4]:
import numpy as np
# Create arrays of different dimensions
array_0d = np . array (5)
array_1d = np . array ([1 , 2 , 3 , 4 , 5])
array_2d = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
array_3d = np . array ([[[1 , 2] , [3 , 4]] , [[5 , 6] , [7 ,8]]])

# Print arrays with shapes
for i , arr in enumerate ([ array_0d , array_1d , array_2d ,array_3d]) :
  print (f"{i}D Array :\n{arr }\nShape : {arr. shape }\n")

0D Array :
5
Shape : ()

1D Array :
[1 2 3 4 5]
Shape : (5,)

2D Array :
[[1 2 3]
 [4 5 6]]
Shape : (2, 3)

3D Array :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape : (2, 2, 2)



In [5]:
import numpy as np
array = np . array ([[1 , 2 , 3] , [4 , 5 , 6]]) # Shape (2 , 3)
reshaped_array = array . reshape (3 , 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape :", array . shape , "\nReshaped Shape :", reshaped_array . shape )

Original Shape : (2, 3) 
Reshaped Shape : (3, 2)


In [6]:
import numpy as np
a = np.arange(1 , 10)
print(a)
x = range(1 , 10)
print(x) # x is an iterator
print(list(x))
# further arange examples :
x = np.arange(10.4)
print(x)
x = np.arange(0.5 , 10.4 , 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [7]:
import numpy as np
# 50 values between 1 and 10:
print ( np . linspace (1 , 10) )
# 7 values between 1 and 10:
print ( np . linspace (1 , 10 , 7) )
# excluding the endpoint :
print ( np . linspace (1 , 10 , 7 , endpoint = False ) )

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [8]:
import numpy as np
# Create arrays of specified shapes
ones_array = np . ones ((2 , 3) ) # Shape : (2 , 3)
zeros_array = np . zeros ((3 , 2) ) # Shape : (3 , 2)
empty_array = np . empty ((2 , 2) ) # Shape : (2 , 2)
identity_matrix = np . eye (3) # Shape : (3 , 3)
print(ones_array , zeros_array , empty_array ,identity_matrix , sep ='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.94242758e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
